version: "3.8"

services:
  # ------------------------------------------------------------------
  # 1. Serviço de Banco de Dados PostgreSQL (postgres_db)
  # ------------------------------------------------------------------
  postgres_db:
    image: postgres:15-alpine
    container_name: nestjs_postgres_local
    env_file:
      - .env
    # environment:
    #   POSTGRES_HOST: postgres_db
    #   POSTGRES_PORT: 5432
    #   POSTGRES_USER: dev_user
    #   POSTGRES_PASSWORD: dev_password
    #   POSTGRES_NAME: retirement_plan_stay_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/01-create-database.sql:/docker-entrypoint-initdb.d/01-create-database.sql
    restart: always

    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U dev_user -d retirement_plan_stay_database"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: my_pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: astesiojose@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: pgadmin_password
  #   ports:
  #     - "8080:80" # Access pgAdmin via http://localhost:8080
  #   depends_on:
  #     - postgres_db

  # ------------------------------------------------------------------
  # 2. Serviço da Aplicação NestJS (api) - Modo Desenvolvimento
  # ------------------------------------------------------------------
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nestjs_api_local
    ports:
      - "3000:3000"
      - "9229:9229" # debug port allowed
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres_db:
        condition: service_healthy
    # command: npm run start:dev
    command: npm run start:container:debug # debug via vscode

volumes:
  postgres_data:
