version: "3.8"

services:
  # ------------------------------------------------------------------
  # 1. Serviço de Banco de Dados PostgreSQL (postgres_db)
  # ------------------------------------------------------------------
  postgres_db:
    image: postgres:15-alpine
    container_name: nestjs_postgres_local
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # ------------------------------------------------------------------
  # 2. Serviço da Aplicação NestJS (api) - Modo Desenvolvimento
  # ------------------------------------------------------------------
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nestjs_api_local
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres_db
    command: npm run start:dev

volumes:
  postgres_data:
